# Generated by Django 5.0.7 on 2024-08-05 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_post_image_alter_category_name_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='newsapp.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(related_name='post_categories', through='newsapp.PostCategory', to='newsapp.category'),
        ),
    ]
