# Generated by Django 5.0.7 on 2024-08-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_post_category_alter_post_postcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(through='newsapp.PostCategory', to='newsapp.category'),
        ),
    ]
