# Generated by Django 5.0.7 on 2024-08-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
