# Generated by Django 5.0.7 on 2024-08-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
